export const universities = [
  {
    name: "Kyungsung University",
    location: "Busan",
    students: "10,000–15,000",
    internationalStudents: "1,966",
    topMajors: ["Global Business Administration", "Global Hospitality Management", "Global Korean Studies", "Global Mechanical Design Engineering", "Global IT Engineering"],
    intake: "March, September",
    tuition: "KRW 3,396,000–5,856,000 per semester",
    overview: "Kyungsung University, located in the vibrant city of Busan, is a private university committed to fostering global talent and innovation.",
    image: "/assets/kyungsung.webp",
    logo: "/assets/ksu_logo.svg",
    videoImage: "/assets/kyungsung.webp",
    homepage: "ks.ac.kr",
    region: "Busan",
    address: "309 Suyeong-ro, Nam-gu, Busan, Republic of Korea, 48434",
    phone: "051-663-4114",
    admissions: [
      { program: "Undergraduate", status: "Admission Closed", tone: "closed" },
      { program: "Graduate (Masters/Ph.D.)", status: "Admission Closed", tone: "closed" },
      { program: "KLP / EAP", status: "Admission Closed", tone: "closed" },
    ],
  },
  {
    name: "Jeonbuk National University",
    location: "Jeonju, Republic of Korea",
    students: "20,000–25,000",
    internationalStudents: "1,112",
    topMajors: ["Glocal Commerce", "K-Entertainment", "Korean Language"],
    intake: "March, September",
    tuition: "KRW 2,016,000–4,048,000 per semester",
    overview: "A leading national university with strong academic reputation and research-oriented programs.",
    image: "/assets/jeonbuk.webp",
    logo: "/assets/jbnu_logo.svg",
    homepage: "www.jbnu.ac.kr",
    region: "Jeolla",
    address: "567 Baekje-daero, Deokjin-gu, Jeonju-si, Jeollabuk-do, Republic of Korea, 54896",
    phone: "063-270-2114",
    admissions: [
      { program: "Undergraduate", status: "Admission Closed", tone: "closed" },
      { program: "Graduate (Masters/Ph.D.)", status: "Admission Closed", tone: "closed" },
      { program: "KLP / EAP", status: "Admission Closed", tone: "closed" },
    ],
  },
  {
    name: "Kyungwoon University",
    location: "Gumi, Republic of Korea",
    students: "5,000–10,000",
    internationalStudents: "909",
    topMajors: ["Global Business Administration", "Global Korean Studies", "Software / IT"],
    intake: "March, September",
    tuition: "KRW 4,120,000 per semester",
    overview: "A specialized university known for aviation, engineering, and applied professional education.",
    image: "/assets/kyungwoon.webp",
    logo: "/assets/kwu_logo.svg",
    homepage: "www.ikw.ac.kr",
    region: "Gyeongsang",
    address: "730 Gangdong-ro, Sandong-eup, Gumi-si, Gyeongsangbuk-do, Republic of Korea, 39160",
    phone: "054-479-1114",
    admissions: [
      { program: "Undergraduate", status: "Not fixed yet", tone: "notfixed" },
      { program: "Graduate (Masters/Ph.D.)", status: "Not fixed yet", tone: "notfixed" },
      { program: "KLP / EAP", status: "Not fixed yet", tone: "notfixed" },
    ],
  },
  {
    name: "Sejong University",
    location: "Seoul, Republic of Korea",
    students: "15,000–20,000",
    internationalStudents: "2,844",
    topMajors: ["Division of Global Leadership", "Department of Public Administration", "Department of Media and Communication", "Faculty of Business Administration", "Department of Economics"],
    intake: "March, September",
    tuition: "KRW 4,669,000–8,367,000 per semester",
    overview: "A well-known university in Seoul with strong programs in hospitality, tourism, business, and technology.",
    image: "/assets/sejong.webp",
    logo: "/assets/sju_logo.svg",
    homepage: "www.sejong.ac.kr",
    region: "Seoul",
    address: "209 Neungdong-ro, Gwangjin-gu, Seoul, Republic of Korea, 05006",
    phone: "02-3408-3114",
    admissions: [
      { program: "Undergraduate", status: "Not fixed yet", tone: "notfixed" },
      { program: "Graduate (Masters/Ph.D.)", status: "Not fixed yet", tone: "notfixed" },
      { program: "KLP / EAP", status: "Not fixed yet", tone: "notfixed" },
    ],
  },
  {
    name: "Youngsan University",
    location: "Yangsan / Haeundae, Republic of Korea",
    students: "2,000–5,000",
    internationalStudents: "842",
    topMajors: ["Department of Hotel and Tourism", "Department of Airline and Tourism", "Department of Tourism and Convention", "Department of Logistics Management", "Global Culinary Major"],
    intake: "March, September",
    tuition: "KRW 3,131,000–3,400,000 per semester",
    overview: "A practice-oriented university with strong hospitality, tourism, and service management programs.",
    image: "/assets/youngsan.webp",
    logo: "/assets/ysu_logo.svg",
    homepage: "www.ysu.ac.kr",
    region: "Busan",
    address: "142 Bansongsunhwan-ro, Haeundae-gu, Busan, Republic of Korea, 48015",
    phone: "051-540-7000",
    admissions: [
      { program: "Undergraduate", status: "Not fixed yet", tone: "notfixed" },
      { program: "Graduate (Masters/Ph.D.)", status: "Not fixed yet", tone: "notfixed" },
      { program: "KLP / EAP", status: "Not fixed yet", tone: "notfixed" },
    ],
  },
] as const;

export type University = typeof universities[number];

export function slugifyUniversity(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
